remove ORCID to debug syw
showyourwork seems to complain when my ORCID is included in \author:
"
Preprocess: Setting up the workflow...
Traceback (most recent call last):
  File "/Users/schlecker/repos/originsoflife/.snakemake/scripts/tmps6etcd0c.preprocess.py", line 495, in <module>
    config["tree"] = get_json_tree(snakemake.input[0])
  File "/Users/schlecker/repos/originsoflife/.snakemake/scripts/tmps6etcd0c.preprocess.py", line 411, in get_json_tree
    free_floating_graphics = [
  File "/Users/schlecker/repos/originsoflife/.snakemake/scripts/tmps6etcd0c.preprocess.py", line 414, in <listcomp>
    if graphic not in config["tex_files_out"]
KeyError: 'tex_files_out'
Error in rule syw__preprocess:
    jobid: 1
    output: .showyourwork/config.json

RuleException:
CalledProcessErrorin line 98 of /Users/schlecker/miniconda3/envs/ool/lib/python3.9/site-packages/showyourwork/workflow/rules/preprocess.smk:
Command 'set -euo pipefail;  /Users/schlecker/miniconda3/envs/ool/bin/python /Users/schlecker/repos/originsoflife/.snakemake/scripts/tmps6etcd0c.preprocess.py' returned non-zero exit status 1.
  File "/Users/schlecker/miniconda3/envs/ool/lib/python3.9/site-packages/showyourwork/workflow/rules/preprocess.smk", line 98, in __rule_4
  File "/Users/schlecker/miniconda3/envs/ool/lib/python3.9/concurrent/futures/thread.py", line 58, in run
Exiting because a job execution failed. Look above for error message
"